# https://atcoder.jp/contests/arc143
# https://atcoder.jp/contests/abc284
# https://atcoder.jp/contests/abc093

run:
	python3 atc/main.py https://atcoder.jp/contests/acl1

.PHONY: in
in:
	python3 main.py < in

.PHONY: test
test:
	pytest -sv
